services:
  client:
    container_name: ace-client
    image: ace-client
    build:
      dockerfile: ./src/client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    container_name: ace-server
    image: ace-server
    build:
      dockerfile: ./src/server/Dockerfile
    ports:
      - "3000:3000"